Fix Basic Auth Configuration for Multiple Paths
Baroshem/nuxt-security pull request #267
Opened 2023-10-26 15:43 UTC by rathahin

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

The existing implementation of basic authentication works partially when multiple routes are specified. The `.some()` method used in the code causes it to return as soon as one matching path is found, leading to incorrect behavior for additional paths. 

This change replaces the `.some()` method with individual variables to track the `exclude` and `include` lists. It uses `.some()` to update these variables and then checks them to decide whether to block the request.

This fix ensures that all specified paths in both the `exclude` and `include` arrays are correctly checked. It provides a clearer and more accurate way to handle basic authentication for multiple routes.

Resolves: #[Issue Number]

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes (if not applicable, please state why)

2023-10-27 10:48 UTC, Baroshem requested changes
One small issue. If you revert it, it should be ready to review and further merge :)

2023-10-27 10:48 UTC, Baroshem commented on pnpm-lock.yaml
issue: this is not needed for sure ;)

2023-10-28 17:03 UTC, rathahin commented on pnpm-lock.yaml
Thank you for pointing out the issue with `pnpm-lock.yaml`. I understand it's not needed and I'll revert it back to its original state. Once that's done, it should be ready for your review and potential merge.

2023-10-30 10:31 UTC, Baroshem approved these changes
Thanks!

2023-10-30 10:51 UTC, Baroshem commented
Hey @rathahin 

Could you please adjust the unit tests to fix the CI?

2023-11-01 06:18 UTC, Baroshem commented
Thanks @rathahin 💚

I will merge it now to the rc branch, conduct some tests and will release a new RC version today :)

2023-11-01 17:32 UTC, merged

2023-11-01 17:33 UTC, Baroshem commented
Thank you @rathahin ! 💚